version: '3'
services:
  db-service:
    build: ./db-service
    volumes:
      - ./db-service:/code
      - /code/node_modules
    command: bash -c "cd /code && npm start"
    depends_on:
      - redis
      - mongo
  users-service:
    build: ./users-service
    ports:
      - 3000:3000
    volumes:
      - ./users-service:/code
      - /code/node_modules
    command: bash -c "cd /code && npm start"
    depends_on:
      - redis
      - mongo
      - db-service
  avatar-service:
    build: ./avatar-service
    ports:
      - 3001:3001
    volumes:
      - ./avatar-service:/code
      - /code/node_modules
    command: bash -c "cd /code && npm start"
    depends_on:
      - redis
      - mongo
      - db-service
  redis:
    image: redis
    ports:
      - 6379:6379
  mongo:
    image: mongo
    ports:
      - 27017:27017